services:
  nginx-proxy:
    container_name: nginx-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./staticfiles:/var/www/staticfiles/
    networks:
      - nginx-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres-db:
    container_name: ${POSTGRES_HOST}
    image: postgres:17.5
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nginx-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  django-app:
    container_name: django-app
    build: .
    restart: always
    #ports:  # expor a porta 8000 para a rede local e externamente
    #  - "8000:8000"
    volumes:
      - ./:/app
      - ./staticfiles:/app/staticfiles
      - ./staticfiles:/staticfiles
      - media:/app/media
    env_file:
      - .env
    networks:
      - nginx-network
    depends_on:
      - postgres-db
      - nginx-proxy
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn --config gunicorn_config.py app.wsgi:application
      "

  backup:
    build: ./backup
    container_name: backup-service
    volumes:
      - postgres_data:/pgdata:ro
      - media:/media:ro
      - ./backups:/backup/output
    env_file:
      - .env
    networks:
      - nginx-network
    depends_on:
      - postgres-db
    restart: unless-stopped

networks:
  nginx-network:
    driver: bridge
    attachable: true

volumes:
  postgres_data:
  media:
  backup: